import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { execFileSync } from 'node:child_process';
import { writeFile, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import Stripe from 'stripe';
import { PDFDocument } from 'pdf-lib';
import { fixture, input, pdfBytes, consent, fakePrepare } from './helpers.js';
import { createApp } from '../src/app.js';
import { prepareDocument } from '../src/documents.js';

test('real HTTP flow: render, preview, protect, demo checkout, repeat protection', async t => {
  const f = await fixture(t, { mode: 'demo' });
  const { app } = await createApp(f.config, f.db, f.providers, { noRateLimit: true });
  const server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
  f.config.baseUrl = `http://127.0.0.1:${server.address().port}`;
  t.after(() => new Promise(resolve => server.close(resolve)));
  const call = (path, options) => fetch(`${f.config.baseUrl}${path}`, options);
  const form = new FormData(); form.set('document', new Blob([await pdfBytes(2)], { type: 'application/pdf' }), 'sample.pdf'); form.set('addresses', JSON.stringify(input));
  const result = await call('/api/orders', { method: 'POST', body: form }); assert.equal(result.status, 201);
  const order = await result.json(), headers = { Authorization: `Bearer ${order.token}`, 'Content-Type': 'application/json' };
  assert.equal(order.amount, 524);
  assert.equal((await call(`/api/orders/${order.id}`)).status, 404);
  assert.equal((await call(`/api/orders/${order.id}/pages/1`)).status, 404);
  const preview = await call(`/api/orders/${order.id}/pages/1`, { headers }); assert.equal(preview.status, 200); assert.match(preview.headers.get('content-type'), /image\/png/);
  assert.equal((await call(`/api/orders/${order.id}/pages/6`, { headers })).status, 404);
  const pdf = await call(`/api/orders/${order.id}/document`, { headers });
  const printed = await PDFDocument.load(await pdf.arrayBuffer()); assert.equal(printed.getPageCount(), 2); assert.deepEqual(printed.getPage(0).getSize(), { width: 612, height: 792 });
  const checkout = await call(`/api/orders/${order.id}/checkout`, { method: 'POST', headers, body: JSON.stringify({ ...consent(order), amount: 1 }) }); assert.equal(checkout.status, 200);
  const status = await (await call(`/api/orders/${order.id}`, { headers })).json(); assert.equal(status.state, 'submitted');
  const duplicate = await call(`/api/orders/${order.id}/checkout`, { method: 'POST', headers, body: JSON.stringify({ confirmed: true }) }); assert.equal(duplicate.status, 409);
  const crossOrigin = await call('/api/orders', { method: 'POST', headers: { Origin: 'https://attacker.invalid' } }); assert.equal(crossOrigin.status, 403);
  const home = await call('/'); assert.ok(home.headers.get('content-security-policy').includes("object-src 'none'")); assert.equal(home.headers.get('referrer-policy'), 'no-referrer');
  assert.equal((await call('/data/papersend.sqlite')).status, 404);
  assert.equal((await call('/.env')).status, 404);
});
test('malformed, oversized-page-count, and encrypted documents never become orders', async t => {
  const f = await fixture(t);
  await assert.rejects(prepareDocument(f.config, 'not-a-pdf', Buffer.from('not pdf')), { status: 400 });
  await assert.rejects(prepareDocument(f.config, 'too-many-pages', await pdfBytes(6)), /1–5 pages/);
  const source = join(f.config.dataDir, 'source.pdf'), encrypted = join(f.config.dataDir, 'encrypted.pdf');
  await writeFile(source, await pdfBytes());
  execFileSync('qpdf', ['--encrypt', 'password', 'owner', '256', '--', source, encrypted]);
  await assert.rejects(prepareDocument(f.config, 'encrypted', await readFile(encrypted)), { status: 400 });
});
test('webhook signatures are required; replay of a real signed event is harmless', async t => {
  const f = await fixture(t, { webhookSecret: 'whsec_papersend_test' });
  const stripe = new Stripe('sk_test_dummy'); f.providers.stripe.webhooks = stripe.webhooks;
  const { app, orders } = await createApp(f.config, f.db, f.providers, { noRateLimit: true, prepare: fakePrepare });
  const server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
  t.after(() => new Promise(resolve => server.close(resolve)));
  const url = `http://127.0.0.1:${server.address().port}/api/webhooks/stripe`;
  const order = await orders.create(input, { buffer: Buffer.from(''), originalname: 'test.pdf' });
  await orders.checkout(order.id, order.token, consent(order));
  const payload = JSON.stringify({ id: 'evt_test', type: 'checkout.session.completed', data: { object: await f.payment(order) } });
  const headers = { 'Content-Type': 'application/json' };
  assert.equal((await fetch(url, { method: 'POST', headers, body: payload })).status, 400);
  headers['stripe-signature'] = stripe.webhooks.generateTestHeaderString({ payload, secret: f.config.webhookSecret });
  for (let n = 0; n < 3; n++) assert.equal((await fetch(url, { method: 'POST', headers, body: payload })).status, 200);
  await orders.work(); assert.equal(f.counts().sends, 1);
});
